//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EldritchArcana.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EldritchArcana.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Enable choosing extra cheat traits,spells(if changed, requires restart for changes to show up). 的本地化字符串。
        /// </summary>
        internal static string CheatCustomTraits_info {
            get {
                return ResourceManager.GetString("CheatCustomTraits_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug logs. 的本地化字符串。
        /// </summary>
        internal static string DrawbackForextraTraits_info {
            get {
                return ResourceManager.GetString("DrawbackForextraTraits_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eldritch Knight requires martial class (doesn&apos;t affect existing EKs). 的本地化字符串。
        /// </summary>
        internal static string EldritchKnightFix_info {
            get {
                return ResourceManager.GetString("EldritchKnightFix_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;Error: Some assets failed to load. Saves using these features won&apos;t work:&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string failedLoading_error {
            get {
                return ResourceManager.GetString("failedLoading_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;Error: Some patches failed to apply. These features may not work:&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string failedPatches_error {
            get {
                return ResourceManager.GetString("failedPatches_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   • &lt;b&gt;{0}&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string featureName_error {
            get {
                return ResourceManager.GetString("featureName_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Give Oracle class 3+int skill points on level up (instead of 4, due to condensed skills). 的本地化字符串。
        /// </summary>
        internal static string OracleHas3SkillPoints_info {
            get {
                return ResourceManager.GetString("OracleHas3SkillPoints_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Any race can choose the Oracle Ancient Lorekeeper archetype. 的本地化字符串。
        /// </summary>
        internal static string RelaxAncientLorekeeper_info {
            get {
                return ResourceManager.GetString("RelaxAncientLorekeeper_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Tongues curse penalty (that party members need 1 rank Knowledge: World to be controlled by PC in combat). 的本地化字符串。
        /// </summary>
        internal static string RelaxTonguesCurse_info {
            get {
                return ResourceManager.GetString("RelaxTonguesCurse_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show custom portraits in the portrait list at character creation (if changed, requires restart). 的本地化字符串。
        /// </summary>
        internal static string ShowCustomPortraits_info {
            get {
                return ResourceManager.GetString("ShowCustomPortraits_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;This mod was tested against game version {0}, but you are running {1}.&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string testedGameVersion_warning {
            get {
                return ResourceManager.GetString("testedGameVersion_warning", resourceCulture);
            }
        }
    }
}
