//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EldritchArcana.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EldritchArcana.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Choose one of your revelations that has a number of uses per day. You gain 1 additional use per day of that revelation.
        ///Special: You can gain this feat multiple times. Its effects do not stack. Each time you take the feat, it applies to a new revelation. 的本地化字符串。
        /// </summary>
        internal static string AbundantRevelationsFeatureDescription_info {
            get {
                return ResourceManager.GetString("AbundantRevelationsFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abundant Revelations 的本地化字符串。
        /// </summary>
        internal static string AbundantRevelationsFeatureName_info {
            get {
                return ResourceManager.GetString("AbundantRevelationsFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scrolls for new spells 的本地化字符串。
        /// </summary>
        internal static string AddSpellScrollsFeatureName_info {
            get {
                return ResourceManager.GetString("AddSpellScrollsFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to apply patch {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string applyPatch_error {
            get {
                return ResourceManager.GetString("applyPatch_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not apply patch for {0} 的本地化字符串。
        /// </summary>
        internal static string applyPath_warning {
            get {
                return ResourceManager.GetString("applyPath_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to apply patch {0}: could not find Harmony attributes 的本地化字符串。
        /// </summary>
        internal static string applyPathHarmony_error {
            get {
                return ResourceManager.GetString("applyPathHarmony_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to apply patch {0}: no dynamic method generated 的本地化字符串。
        /// </summary>
        internal static string applyPathMethod {
            get {
                return ResourceManager.GetString("applyPathMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///You can also add any metamagic feats that you know to your spells without increasing their casting time, although you must still expend higher-level spell slots. 的本地化字符串。
        /// </summary>
        internal static string ArcaneApotheosisFeatureDescription_info {
            get {
                return ResourceManager.GetString("ArcaneApotheosisFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You gain the orc subtype, including light sensitivity. Whenever you cast a spell that deals damage, that spell deals +1 point of damage per die rolled. 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcArcanaFeatureDescription_info {
            get {
                return ResourceManager.GetString("BloodlineOrcArcanaFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orc Bloodline Arcana 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcArcanaFeatureName_info {
            get {
                return ResourceManager.GetString("BloodlineOrcArcanaFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At 3rd level, you gain a +4 bonus on saving throws made against fear and a +1 natural armor bonus. At 9th level, you lose your light sensitivity, gain immunity to fear, and your natural armor bonus increases to +2. 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcFearlessFeatureDescription_info {
            get {
                return ResourceManager.GetString("BloodlineOrcFearlessFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fearless 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcFearlessFeatureName_info {
            get {
                return ResourceManager.GetString("BloodlineOrcFearlessFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creatures with light sensitivity are dazzled in areas of bright sunlight or within the radius of a daylight spell. 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcLightSensitivityFeatureDescription_info {
            get {
                return ResourceManager.GetString("BloodlineOrcLightSensitivityFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Sensitivity 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcLightSensitivityFeatureName_info {
            get {
                return ResourceManager.GetString("BloodlineOrcLightSensitivityFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At 2nd level, and every two levels thereafter, an oracle learns an additional spell derived from their mystery. 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcOracleSpellDescription_info {
            get {
                return ResourceManager.GetString("BloodlineOrcOracleSpellDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At 15th level, you may grow to Large size as a standard action. At this size you gain a +6 size bonus to Strength, a –2 penalty to Dexterity, a +4 size bonus to Constitution, and a +4 natural armor bonus. You may return to your normal size as a standard action. You may remain in this size for up to 1 minute per character level per day; this duration does not need to be consecutive, but it must be used in 1 minute increments. 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcPowerOfGiantsBuffDescription_info {
            get {
                return ResourceManager.GetString("BloodlineOrcPowerOfGiantsBuffDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power of Giants 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcPowerOfGiantsBuffName_info {
            get {
                return ResourceManager.GetString("BloodlineOrcPowerOfGiantsBuffName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At 3rd level, and every two levels thereafter, a sorcerer learns an additional spell derived from their bloodline. 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcSpellDescription_info {
            get {
                return ResourceManager.GetString("BloodlineOrcSpellDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}These spells cannot be exchanged for different spells at higher levels.
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcSpellFeatureDescription_info {
            get {
                return ResourceManager.GetString("BloodlineOrcSpellFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At 9th level, you gain a +2 inherent bonus to your Strength. This bonus increases to +4 at 13th level, and to +6 at 17th level. 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcStrengthOfTheBeastFeatureDescription_info {
            get {
                return ResourceManager.GetString("BloodlineOrcStrengthOfTheBeastFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strength of the Beast 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcStrengthOfTheBeastFeatureName_info {
            get {
                return ResourceManager.GetString("BloodlineOrcStrengthOfTheBeastFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At 1st level, you can touch a creature as a standard action, giving it a morale bonus on attack rolls, damage rolls, and Will saving throws equal to 1/2 your sorcerer level (minimum 1) for 1 round. You can use this ability a number of times per day equal to 3 + your Charisma modifier. 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcTouchOfRageBuffDescription_info {
            get {
                return ResourceManager.GetString("BloodlineOrcTouchOfRageBuffDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touch of Rage 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcTouchOfRageBuffName_info {
            get {
                return ResourceManager.GetString("BloodlineOrcTouchOfRageBuffName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At 20th level, you become a true orc warlord of legend. You gain immunity to fire and DR 5/—. Once per day, you can cast transformation as a spell-like ability using your sorcerer level as your caster level. 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcWarlordRebornFeatureDescription_info {
            get {
                return ResourceManager.GetString("BloodlineOrcWarlordRebornFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warlord Reborn 的本地化字符串。
        /// </summary>
        internal static string BloodlineOrcWarlordRebornFeatureName_info {
            get {
                return ResourceManager.GetString("BloodlineOrcWarlordRebornFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to patch LibraryScriptableObject.LoadDictionary(), cannot load mod! 的本地化字符串。
        /// </summary>
        internal static string cannotLoadMod_error {
            get {
                return ResourceManager.GetString("cannotLoadMod_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can channel positive energy like a cleric, using your oracle level as your effective cleric level when determining the amount of damage healed (or caused to undead) and the DC.
        ///You can use this ability a number of times per day equal to 1+your Charisma modifier. 的本地化字符串。
        /// </summary>
        internal static string ChannelEnergyFeatureDescription_info {
            get {
                return ResourceManager.GetString("ChannelEnergyFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel Energy 的本地化字符串。
        /// </summary>
        internal static string ChannelEnergyFeatureName_info {
            get {
                return ResourceManager.GetString("ChannelEnergyFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable choosing extra cheat traits,spells(if changed, requires restart for changes to show up) 的本地化字符串。
        /// </summary>
        internal static string CheatCustomTraits_info {
            get {
                return ResourceManager.GetString("CheatCustomTraits_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Once per day as an immediate action, whenever you fail a saving throw against a disease or poison, you may ignore its effects for 1 hour per level. At 7th and 15th level, you can use this ability one additional time per day. 的本地化字符串。
        /// </summary>
        internal static string DelayAfflictionFeatureDescription_info {
            get {
                return ResourceManager.GetString("DelayAfflictionFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay Affliction 的本地化字符串。
        /// </summary>
        internal static string DelayAfflictionFeatureName_info {
            get {
                return ResourceManager.GetString("DelayAfflictionFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When wielding a scimitar with one hand, you can use your Dexterity modifier instead of your Strength modifier on melee attack and damage rolls. You treat the scimitar as a one-handed piercing weapon for all feats and class abilities that require such a weapon (such as a duelist&apos;s precise strike ability). The scimitar must be for a creature of your size. You cannot use this feat if you are carrying a weapon or shield in your off hand. 的本地化字符串。
        /// </summary>
        internal static string DervishDanceFeatureDescription_info {
            get {
                return ResourceManager.GetString("DervishDanceFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dervish Dance 的本地化字符串。
        /// </summary>
        internal static string DervishDanceFeatureName_info {
            get {
                return ResourceManager.GetString("DervishDanceFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can detect secret doors, compartments, caches, and so forth. Only passages, doors, or openings that have been specifically constructed to escape detection are detected by this spell.
        ///Each round, you can turn to detect secret doors in a new area. This spell requires concentration, and will end prematurely if you cast another spell, take a standard action, or fail a concentration check. 的本地化字符串。
        /// </summary>
        internal static string DetectSecretDoorsAbilityDescription_info {
            get {
                return ResourceManager.GetString("DetectSecretDoorsAbilityDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 concentration, up to 1 min/level 的本地化字符串。
        /// </summary>
        internal static string DetectSecretDoorsAbilityDuration_info {
            get {
                return ResourceManager.GetString("DetectSecretDoorsAbilityDuration_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect Secret Doors: found hidden door. 的本地化字符串。
        /// </summary>
        internal static string DetectSecretDoorsFoundDoorLog_info {
            get {
                return ResourceManager.GetString("DetectSecretDoorsFoundDoorLog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect Secret Doors: found hidden item. 的本地化字符串。
        /// </summary>
        internal static string DetectSecretDoorsFoundItemLog_info {
            get {
                return ResourceManager.GetString("DetectSecretDoorsFoundItemLog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect Secret Doors 的本地化字符串。
        /// </summary>
        internal static string DetectSecretDoorsSpells_info {
            get {
                return ResourceManager.GetString("DetectSecretDoorsSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ability to dismiss area effects 的本地化字符串。
        /// </summary>
        internal static string DismissSpells_info {
            get {
                return ResourceManager.GetString("DismissSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabling feats with drawback 的本地化字符串。
        /// </summary>
        internal static string DrawbackForextraTraits_info {
            get {
                return ResourceManager.GetString("DrawbackForextraTraits_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you pick a Drawback at level one you can choose an extra feat on top.
        ///You have A frail body and you break bones easily also your health is not great so you have -1 vs disease saves.
        ///Drawback: -3 hp at level 1 and You lose 1 additional hit points.For every Hit Die you possess. 的本地化字符串。
        /// </summary>
        internal static string DrawbackFrailFeatureDescription_info {
            get {
                return ResourceManager.GetString("DrawbackFrailFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frail 的本地化字符串。
        /// </summary>
        internal static string DrawbackFrailFeatureName_info {
            get {
                return ResourceManager.GetString("DrawbackFrailFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you pick a Drawback at level one you can choose an extra feat on top.
        ///Drawback: Even with a peg leg, you lose 10 feet from your race抯 normal speed.
        ///Drawback: You lose 2 initiative. 的本地化字符串。
        /// </summary>
        internal static string DrawbackOneLeggedFeatureDescription_info {
            get {
                return ResourceManager.GetString("DrawbackOneLeggedFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peg leg 的本地化字符串。
        /// </summary>
        internal static string DrawbackOneLeggedFeatureName_info {
            get {
                return ResourceManager.GetString("DrawbackOneLeggedFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you pick a Drawback at level one you can choose an extra feat on top.
        ///Bane: choose a spellschool you have {0} on saves vs that spellschool. 的本地化字符串。
        /// </summary>
        internal static string DrawbackSpellVulnerabilityFeatureDescription_info {
            get {
                return ResourceManager.GetString("DrawbackSpellVulnerabilityFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spell Vulnerability 的本地化字符串。
        /// </summary>
        internal static string DrawbackSpellVulnerabilityFeatureName_info {
            get {
                return ResourceManager.GetString("DrawbackSpellVulnerabilityFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eldritch Knight requires martial class 的本地化字符串。
        /// </summary>
        internal static string EldritchKnightFix_info {
            get {
                return ResourceManager.GetString("EldritchKnightFix_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 doesn&apos;t affect existing EKs 的本地化字符串。
        /// </summary>
        internal static string EldritchKnightFix_tip {
            get {
                return ResourceManager.GetString("EldritchKnightFix_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency force sphere 的本地化字符串。
        /// </summary>
        internal static string EmergencyForceSphereSpells_info {
            get {
                return ResourceManager.GetString("EmergencyForceSphereSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 As a standard action, you can transform your body into pure life energy, resembling a golden-white fire elemental. In this form, you gain the elemental subtype and give off a warm, welcoming light that increases the light level within 10 feet by one step, up to normal light. Any undead creature striking you with its body or a handheld weapon deals normal damage, but at the same time the attacker takes 1d6 points of positive energy damage + 1 point per oracle level. Creatures wielding melee weapons with reac [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string EnergyBodyFeatureDescription_info {
            get {
                return ResourceManager.GetString("EnergyBodyFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Energy Body 的本地化字符串。
        /// </summary>
        internal static string EnergyBodyFeatureName_info {
            get {
                return ResourceManager.GetString("EnergyBodyFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whenever you cast a cure spell, the maximum number of hit points healed is based on your oracle level, not the limit based on the spell. For example, an 11th-level oracle of life with this revelation may cast cure light wounds to heal 1d8+11 hit points instead of the normal 1d8+5 maximum. 的本地化字符串。
        /// </summary>
        internal static string EnhancedCuresFeatureDescription_info {
            get {
                return ResourceManager.GetString("EnhancedCuresFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enhanced Cures 的本地化字符串。
        /// </summary>
        internal static string EnhancedCuresFeatureName_info {
            get {
                return ResourceManager.GetString("EnhancedCuresFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have unlocked the secret of a new magus arcana. You gain one additional magus arcana. You must meet all the prerequisites for this magus arcana.
        ///Special: You can gain this feat multiple times. Its effects stack, granting a new arcana each time you gain this feat. 的本地化字符串。
        /// </summary>
        internal static string ExtraArcanaFeatureDescription_info {
            get {
                return ResourceManager.GetString("ExtraArcanaFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Arcana 的本地化字符串。
        /// </summary>
        internal static string ExtraArcanaFeatureName_info {
            get {
                return ResourceManager.GetString("ExtraArcanaFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You gain one additional revelation. You must meet all of the prerequisites for this revelation.
        ///Special: You can gain Extra Revelation multiple times. 的本地化字符串。
        /// </summary>
        internal static string ExtraRevelationFeatureDescription_info {
            get {
                return ResourceManager.GetString("ExtraRevelationFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Revelation 的本地化字符串。
        /// </summary>
        internal static string ExtraRevelationFeatureName_info {
            get {
                return ResourceManager.GetString("ExtraRevelationFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;Error: Some assets failed to load. Saves using these features won&apos;t work:&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string failedLoading_error {
            get {
                return ResourceManager.GetString("failedLoading_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;Error: Some patches failed to apply. These features may not work:&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string failedPatches_error {
            get {
                return ResourceManager.GetString("failedPatches_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   • &lt;b&gt;{0}&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string featureName_error {
            get {
                return ResourceManager.GetString("featureName_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All mod features 的本地化字符串。
        /// </summary>
        internal static string featureNameAll_error {
            get {
                return ResourceManager.GetString("featureNameAll_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You were found in the wilds as a child.
        ///Whenever you receive magical healing, you heal an additional 2 points per die rolled. You gain a +2 bonus on all saving throws against death effects. Unfortunately, you also suffer +1 point of damage from cold iron weapons (although you can wield cold iron weapons without significant discomfort). 的本地化字符串。
        /// </summary>
        internal static string FeyFoundlingFeatureDescription_info {
            get {
                return ResourceManager.GetString("FeyFoundlingFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fey Foundling 的本地化字符串。
        /// </summary>
        internal static string FeyFoundlingFeatureName_info {
            get {
                return ResourceManager.GetString("FeyFoundlingFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upon reaching 20th level, you become a perfect channel for life energy. You become immune to bleed, death attacks, exhaustion, fatigue, nausea effects, negative levels, and sickened effects. Ability damage and drain cannot reduce you below 1 in any ability score. 的本地化字符串。
        /// </summary>
        internal static string FinalRevelationFeatureDescription_info {
            get {
                return ResourceManager.GetString("FinalRevelationFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Final Revelation 的本地化字符串。
        /// </summary>
        internal static string FinalRevelationFeatureName_info {
            get {
                return ResourceManager.GetString("FinalRevelationFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fire spells 的本地化字符串。
        /// </summary>
        internal static string FireSpells_info {
            get {
                return ResourceManager.GetString("FireSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At 3rd level, and every two levels thereafter, a sorcerer learns an additional spell, derived from her bloodline. These spells are in addition to the number of spells given at new levels.
        /// 的本地化字符串。
        /// </summary>
        internal static string FixBloodlineSpellDescriptionPrefix_info {
            get {
                return ResourceManager.GetString("FixBloodlineSpellDescriptionPrefix_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable spellcasting for elemental forms 的本地化字符串。
        /// </summary>
        internal static string FixElementalSpells_info {
            get {
                return ResourceManager.GetString("FixElementalSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spell Specialization 的本地化字符串。
        /// </summary>
        internal static string FixSpellSpecializationFeatureName_info {
            get {
                return ResourceManager.GetString("FixSpellSpecializationFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fly and Air Walk spells 的本地化字符串。
        /// </summary>
        internal static string FlySpells_info {
            get {
                return ResourceManager.GetString("FlySpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This spell summons to your side a sextuple band of goblin creatures. The summoned band appears where you designate and acts immediately, on your turn. It attacks your opponents to the best of its ability. If you can communicate with the creature, you can direct it not to attack, to attack particular enemies, or to perform other actions as you command. 的本地化字符串。
        /// </summary>
        internal static string GoblinSpellDescription_info {
            get {
                return ResourceManager.GetString("GoblinSpellDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summon Six Goblins 的本地化字符串。
        /// </summary>
        internal static string GoblinSpellName_info {
            get {
                return ResourceManager.GetString("GoblinSpellName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This spell functions like magic weapon, except that it gives a weapon an enhancement bonus on attack and damage rolls of +1 per four caster levels (maximum +5). This bonus does not allow a weapon to bypass damage reduction aside from magic. 的本地化字符串。
        /// </summary>
        internal static string GreaterMagicWeaponAbilityDescription_info {
            get {
                return ResourceManager.GetString("GreaterMagicWeaponAbilityDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greater Magic Weapon 的本地化字符串。
        /// </summary>
        internal static string GreaterMagicWeaponSpells_info {
            get {
                return ResourceManager.GetString("GreaterMagicWeaponSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You gain a +4 bonus on Heal checks. You may use {0} as a swift action. 的本地化字符串。
        /// </summary>
        internal static string HealingHandsFeatureDescription_info {
            get {
                return ResourceManager.GetString("HealingHandsFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Healing Hands 的本地化字符串。
        /// </summary>
        internal static string HealingHandsFeatureName_info {
            get {
                return ResourceManager.GetString("HealingHandsFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outlander spells gain caster level and DC max (cheat) 的本地化字符串。
        /// </summary>
        internal static string HighDCl_info {
            get {
                return ResourceManager.GetString("HighDCl_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Concentration + 2 rounds 的本地化字符串。
        /// </summary>
        internal static string HypnoticDurationLocalized_info {
            get {
                return ResourceManager.GetString("HypnoticDurationLocalized_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hypnotic Pattern 的本地化字符串。
        /// </summary>
        internal static string HypnoticPatternSpells_info {
            get {
                return ResourceManager.GetString("HypnoticPatternSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A twisting pattern of subtle, shifting colors weaves through the air, fascinating creatures within it. Roll 2d4 and add your caster level (maximum 10) to determine the total number of HD of creatures affected. Creatures with the fewest HD are affected first; and, among creatures with equal HD, those who are closest to the spell&apos;s point of origin are affected first. HD that are not sufficient to affect a creature are wasted. Affected creatures become fascinated by the pattern of colors. Sightless creatures a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HypnoticSpellDescription_info {
            get {
                return ResourceManager.GetString("HypnoticSpellDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose this to skip replacing a known spell this level. 的本地化字符串。
        /// </summary>
        internal static string KeepAllSpellsFeatureDescription_info {
            get {
                return ResourceManager.GetString("KeepAllSpellsFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep all spells 的本地化字符串。
        /// </summary>
        internal static string KeepAllSpellsFeatureName_info {
            get {
                return ResourceManager.GetString("KeepAllSpellsFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Knock opens stuck, barred, or locked doors, as well as those subject to hold portal or arcane lock. When you complete the casting of this spell, make a caster level check against the DC of the lock with a +10 bonus. If successful, knock opens up to two means of closure. This spell opens secret doors, as well as locked or trick-opening boxes or chests. It also loosens welds, shackles, or chains (provided they serve to hold something shut). If used to open an arcane locked door, the spell does not remove the  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string KnockAbilityDescription_info {
            get {
                return ResourceManager.GetString("KnockAbilityDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Knock and Detect Secret Doors 的本地化字符串。
        /// </summary>
        internal static string KnockAndDetectSecretsSpells_info {
            get {
                return ResourceManager.GetString("KnockAndDetectSecretsSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This spell functions as knock, but works on multiple means of closure at once (up to 1/caster level).
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string KnockMassAbilityDescription_info {
            get {
                return ResourceManager.GetString("KnockMassAbilityDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Knock, Mass 的本地化字符串。
        /// </summary>
        internal static string KnockMassAbilityName_info {
            get {
                return ResourceManager.GetString("KnockMassAbilityName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Knock failed to open lock. 的本地化字符串。
        /// </summary>
        internal static string KnockOpenLockFailLog_info {
            get {
                return ResourceManager.GetString("KnockOpenLockFailLog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Knock successfully opened lock. 的本地化字符串。
        /// </summary>
        internal static string KnockOpenLockSuccessLog_info {
            get {
                return ResourceManager.GetString("KnockOpenLockSuccessLog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Knock result: {0} (roll {1} + caster level {2} + bonus 10).
        ///Difficulty Class (DC): {3}.
        /// 的本地化字符串。
        /// </summary>
        internal static string KnockResultLog_info {
            get {
                return ResourceManager.GetString("KnockResultLog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Knock 的本地化字符串。
        /// </summary>
        internal static string KnockSpells_info {
            get {
                return ResourceManager.GetString("KnockSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t so much cast a miracle as request one. You state what you would like to have happen and request that your deity (or the power you pray to for spells) intercede.
        ///A miracle can do any of the following things.
        ///• Duplicate any cleric spell of 8th level or lower.
        ///• Duplicate any other spell of 7th level or lower.
        ///• Undo the harmful effects of certain spells, such as feeblemind or insanity.
        ///• Have any effect whose power level is in line with the above effects.
        ///Alternatively, a cleric can make a ve [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string LesserMiracleAbilityDescription_info {
            get {
                return ResourceManager.GetString("LesserMiracleAbilityDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Divine) Miracle 的本地化字符串。
        /// </summary>
        internal static string LesserMiracleAbilityName_info {
            get {
                return ResourceManager.GetString("LesserMiracleAbilityName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Miracle preloading 的本地化字符串。
        /// </summary>
        internal static string LesserMiracleSpells_info {
            get {
                return ResourceManager.GetString("LesserMiracleSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  (spell level {0}) 的本地化字符串。
        /// </summary>
        internal static string LevelSpellNamePostfix_info {
            get {
                return ResourceManager.GetString("LevelSpellNamePostfix_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 As a standard action, you may create a bond between yourself and another creature. Each round at the start of your turn, if the bonded creature is wounded for 5 or more hit points below its maximum hit points, it heals 5 hit points and you take 5 hit points of damage. You may have one bond active per oracle level. This bond continues until the bonded creature dies, you die, the distance between you and the other creature exceeds medium range, or you end it as an immediate action (if you have multiple bonds  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string LifeLinkFeatureDescription_info {
            get {
                return ResourceManager.GetString("LifeLinkFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Life Link 的本地化字符串。
        /// </summary>
        internal static string LifeLinkFeatureName_info {
            get {
                return ResourceManager.GetString("LifeLinkFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class skills: {0}, {1}
        ///An oracle with the life mystery can choose from any of the following revelations: 的本地化字符串。
        /// </summary>
        internal static string LifeMysteryProgressionDescription_info {
            get {
                return ResourceManager.GetString("LifeMysteryProgressionDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Life Mystery 的本地化字符串。
        /// </summary>
        internal static string LifeMysteryProgressionName_info {
            get {
                return ResourceManager.GetString("LifeMysteryProgressionName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not active on any targets. 的本地化字符串。
        /// </summary>
        internal static string LifeMysteryReason_error {
            get {
                return ResourceManager.GetString("LifeMysteryReason_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Life Revelation 的本地化字符串。
        /// </summary>
        internal static string LifeRevelationFeatureName_info {
            get {
                return ResourceManager.GetString("LifeRevelationFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You notice and locate living creatures within 30 feet, just as if you possessed the blindsight ability. You must be at least 11th level to select this revelation. 的本地化字符串。
        /// </summary>
        internal static string LifeSenseFeatureDescription_info {
            get {
                return ResourceManager.GetString("LifeSenseFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Life Sense 的本地化字符串。
        /// </summary>
        internal static string LifeSenseFeatureName_info {
            get {
                return ResourceManager.GetString("LifeSenseFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A limited wish lets you create nearly any type of effect. For example, a limited wish can do any of the following things.
        ///• Duplicate any sorcerer/wizard spell of 6th level or lower, provided the spell does not belong to one of your opposition schools.
        ///• Duplicate any non-sorcerer/wizard spell of 5th level or lower, provided the spell does not belong to one of your opposition schools.
        ///• Duplicate any sorcerer/wizard spell of 5th level or lower, even if it belongs to one of your opposition schools.
        ///• Dup [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string LimitedWishAbilityDescription_info {
            get {
                return ResourceManager.GetString("LimitedWishAbilityDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limited Wish 的本地化字符串。
        /// </summary>
        internal static string LimitedWishSpells_info {
            get {
                return ResourceManager.GetString("LimitedWishSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bloodlines 的本地化字符串。
        /// </summary>
        internal static string loadBloodlines_error {
            get {
                return ResourceManager.GetString("loadBloodlines_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crossblooded Sorcerer 的本地化字符串。
        /// </summary>
        internal static string loadCrossbloodedSorcerer_error {
            get {
                return ResourceManager.GetString("loadCrossbloodedSorcerer_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Portraits in main portrait selection 的本地化字符串。
        /// </summary>
        internal static string LoadCustomPortraits_error {
            get {
                return ResourceManager.GetString("LoadCustomPortraits_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drawback Feats 的本地化字符串。
        /// </summary>
        internal static string loadDrawbackFeats_error {
            get {
                return ResourceManager.GetString("loadDrawbackFeats_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eldritch Heritage 的本地化字符串。
        /// </summary>
        internal static string loadEldritchHeritage_error {
            get {
                return ResourceManager.GetString("loadEldritchHeritage_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favored class bonus, deity selection 的本地化字符串。
        /// </summary>
        internal static string loadFavoredClassBonus_error {
            get {
                return ResourceManager.GetString("loadFavoredClassBonus_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialization code 的本地化字符串。
        /// </summary>
        internal static string loadHelpers_error {
            get {
                return ResourceManager.GetString("loadHelpers_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magic feats 的本地化字符串。
        /// </summary>
        internal static string loadMagicFeats_error {
            get {
                return ResourceManager.GetString("loadMagicFeats_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oracle class 的本地化字符串。
        /// </summary>
        internal static string loadOracleClass_error {
            get {
                return ResourceManager.GetString("loadOracleClass_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prestigious Spellcaster 的本地化字符串。
        /// </summary>
        internal static string loadPrestigiousSpellcaster_error {
            get {
                return ResourceManager.GetString("loadPrestigiousSpellcaster_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spell replacement for spontaneous casters 的本地化字符串。
        /// </summary>
        internal static string loadReplaceSpells_error {
            get {
                return ResourceManager.GetString("loadReplaceSpells_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New spells 的本地化字符串。
        /// </summary>
        internal static string loadSpells_error {
            get {
                return ResourceManager.GetString("loadSpells_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traits 的本地化字符串。
        /// </summary>
        internal static string loadTraits_error {
            get {
                return ResourceManager.GetString("loadTraits_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wish spells 的本地化字符串。
        /// </summary>
        internal static string loadWishSpells_error {
            get {
                return ResourceManager.GetString("loadWishSpells_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a school of magic in which you have Spell Focus—you cast spells from this school at +1 caster level. 的本地化字符串。
        /// </summary>
        internal static string MagesTattooFeatureDescription_info {
            get {
                return ResourceManager.GetString("MagesTattooFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mage&apos;s Tattoo 的本地化字符串。
        /// </summary>
        internal static string MagesTattooFeatureName_info {
            get {
                return ResourceManager.GetString("MagesTattooFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magus Arcanas 的本地化字符串。
        /// </summary>
        internal static string MagusArcanasFeatureName_info {
            get {
                return ResourceManager.GetString("MagusArcanasFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The magus gains a familiar, using their magus level as their effective wizard level. This familiar follows the rules for familiars presented in the arcane bond wizard class feature. 的本地化字符串。
        /// </summary>
        internal static string MagusFamiliarFeatureDescription_info {
            get {
                return ResourceManager.GetString("MagusFamiliarFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Familiar 的本地化字符串。
        /// </summary>
        internal static string MagusFamiliarFeatureName_info {
            get {
                return ResourceManager.GetString("MagusFamiliarFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This does not increase the casting time or the level of the spell. 的本地化字符串。
        /// </summary>
        internal static string MagusMagicCastTimeLevelFeatureDescription_info {
            get {
                return ResourceManager.GetString("MagusMagicCastTimeLevelFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The magus can cast one spell per day as if it were modified by the {0} Spell feat.  的本地化字符串。
        /// </summary>
        internal static string MagusMagicFeatureDescription_info {
            get {
                return ResourceManager.GetString("MagusMagicFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Magic 的本地化字符串。
        /// </summary>
        internal static string MagusMagicFeatureName_info {
            get {
                return ResourceManager.GetString("MagusMagicFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This does not increase the level of the spell. 的本地化字符串。
        /// </summary>
        internal static string MagusMagicLevelFeatureDescription_info {
            get {
                return ResourceManager.GetString("MagusMagicLevelFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At 3rd level, you can apply any one metamagic feat you know to a spell you are about to cast without increasing the casting time. You must still expend a higher-level spell slot to cast this spell. You can use this ability once per day at 3rd level and one additional time per day for every four sorcerer levels you possess beyond 3rd, up to five times per day at 19th level. At 20th level, this ability is replaced by arcane apotheosis. 的本地化字符串。
        /// </summary>
        internal static string MetamagicAdeptFeatureDescription_info {
            get {
                return ResourceManager.GetString("MetamagicAdeptFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metamagic Adept (Arcane Bloodline) 的本地化字符串。
        /// </summary>
        internal static string MetamagicAdeptFeatureName_info {
            get {
                return ResourceManager.GetString("MetamagicAdeptFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metamagic feats 的本地化字符串。
        /// </summary>
        internal static string MetamagicFeatsFeatureName_info {
            get {
                return ResourceManager.GetString("MetamagicFeatsFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t so much cast a miracle as request one. You state what you would like to have happen and request that your deity (or the power you pray to for spells) intercede.
        ///A miracle can do any of the following things.
        ///• Duplicate any cleric spell of 8th level or lower.
        ///• Duplicate any other spell of 7th level or lower.
        ///• Undo the harmful effects of certain spells, such as feeblemind or insanity.
        ///• Have any effect whose power level is in line with the above effects.
        ///Alternatively, a cleric can make a ve [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MiracleAbilityDescription_info {
            get {
                return ResourceManager.GetString("MiracleAbilityDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Miracle 的本地化字符串。
        /// </summary>
        internal static string MiracleSpells_info {
            get {
                return ResourceManager.GetString("MiracleSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oracles receive additional class skills depending upon their oracle mystery. 的本地化字符串。
        /// </summary>
        internal static string MysteryClassSkillsFeatureDescription_info {
            get {
                return ResourceManager.GetString("MysteryClassSkillsFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bonus Class Skills 的本地化字符串。
        /// </summary>
        internal static string MysteryClassSkillsFeatureName_info {
            get {
                return ResourceManager.GetString("MysteryClassSkillsFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select one Wizard opposition school; preparing spells of this school now only requires one spell slot of the appropriate level instead of two, and you no longer have the –4 Spellcraft penalty for crafting items from that school. 的本地化字符串。
        /// </summary>
        internal static string OppositionResearchFeatureDescription_info {
            get {
                return ResourceManager.GetString("OppositionResearchFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opposition Research 的本地化字符串。
        /// </summary>
        internal static string OppositionResearchFeatureName_info {
            get {
                return ResourceManager.GetString("OppositionResearchFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In addition to the spells gained by oracles as they gain levels, each oracle also adds all of either the cure spells or the inflict spells to her list of spells known (cure spells include all spells with &quot;cure&quot; in the name, inflict spells include all spells with &quot;inflict&quot; in the name). These spells are added as soon as the oracle is capable of casting them. This choice is made when the oracle gains her first level and cannot be changed. 的本地化字符串。
        /// </summary>
        internal static string OracleCureOrInflictSpellFeatureDescription_info {
            get {
                return ResourceManager.GetString("OracleCureOrInflictSpellFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cure or Inflict Spells 的本地化字符串。
        /// </summary>
        internal static string OracleCureOrInflictSpellFeatureName_info {
            get {
                return ResourceManager.GetString("OracleCureOrInflictSpellFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cure Spells 的本地化字符串。
        /// </summary>
        internal static string OracleCureSpellProgressionName_info {
            get {
                return ResourceManager.GetString("OracleCureSpellProgressionName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Give Oracle class 3+int skill points on level up (instead of 4, due to condensed skills) 的本地化字符串。
        /// </summary>
        internal static string OracleHas3SkillPoints_info {
            get {
                return ResourceManager.GetString("OracleHas3SkillPoints_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inflict Spells 的本地化字符串。
        /// </summary>
        internal static string OracleInflictSpellProgressionName_info {
            get {
                return ResourceManager.GetString("OracleInflictSpellProgressionName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Although the gods work through many agents, perhaps none is more mysterious than the oracle. These divine vessels are granted power without their choice, selected by providence to wield powers that even they do not fully understand. Unlike a cleric, who draws her magic through devotion to a deity, oracles garner strength and power from many sources, namely those patron deities who support their ideals. Instead of worshiping a single source, oracles tend to venerate all of the gods that share their beliefs.  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string OracleLocalizedDescription_info {
            get {
                return ResourceManager.GetString("OracleLocalizedDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oracle 的本地化字符串。
        /// </summary>
        internal static string OracleLocalizedName_info {
            get {
                return ResourceManager.GetString("OracleLocalizedName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each oracle draws upon a divine mystery to grant her spells and powers. This mystery also grants additional class skills and other special abilities. This mystery can represent a devotion to one ideal, prayers to deities that support the concept, or a natural calling to champion a cause. For example, an oracle with the waves mystery might have been born at sea and found a natural calling to worship the gods of the oceans, rivers, and lakes, be they benign or malevolent. Regardless of its source, the mystery [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string OracleMysteryFeatureDescription_info {
            get {
                return ResourceManager.GetString("OracleMysteryFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mystery 的本地化字符串。
        /// </summary>
        internal static string OracleMysteryFeatureName_info {
            get {
                return ResourceManager.GetString("OracleMysteryFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oracles learn a number of orisons, or 0-level spells. These spells are cast like any other spell, but they do not consume any slots and may be used again. 的本地化字符串。
        /// </summary>
        internal static string OracleOrisonsFeatureDescription_info {
            get {
                return ResourceManager.GetString("OracleOrisonsFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oracles are proficient with all simple weapons, light armor, medium armor, and shields (except tower shields). Some oracle revelations grant additional proficiencies. 的本地化字符串。
        /// </summary>
        internal static string OracleProficienciesFeatureDescription_info {
            get {
                return ResourceManager.GetString("OracleProficienciesFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oracle Proficiencies 的本地化字符串。
        /// </summary>
        internal static string OracleProficienciesFeatureName_info {
            get {
                return ResourceManager.GetString("OracleProficienciesFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At 1st level, 3rd level, and every four levels thereafter (7th, 11th, and so on), an oracle uncovers a new secret about her mystery that grants her powers and abilities. The oracle must select a revelation from the list of revelations available to her mystery (see FAQ at right). If a revelation is chosen at a later level, the oracle gains all of the abilities and bonuses granted by that revelation based on her current level. Unless otherwise noted, activating the power of a revelation is a standard action.        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string OracleRevelationFeatureDescription_info {
            get {
                return ResourceManager.GetString("OracleRevelationFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Revelation 的本地化字符串。
        /// </summary>
        internal static string OracleRevelationFeatureName_info {
            get {
                return ResourceManager.GetString("OracleRevelationFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The rage of your ancestors burns within you, and the taint of savage orc blood flows through your veins. Your anger is never far from the surface, giving you strength and driving you to seek greater power.
        ///Bonus Feats of the Orc Bloodline: Diehard, Endurance, Great Fortitude, Intimidating Prowess, Improved Bull Rush, Power Attack, Toughness, Reach Spell. 的本地化字符串。
        /// </summary>
        internal static string OrcBloodlineFeatureDescription_info {
            get {
                return ResourceManager.GetString("OrcBloodlineFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orc Bloodline 的本地化字符串。
        /// </summary>
        internal static string OrcBloodlineFeatureName_info {
            get {
                return ResourceManager.GetString("OrcBloodlineFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Any race can choose the Oracle Ancient Lorekeeper archetype 的本地化字符串。
        /// </summary>
        internal static string RelaxAncientLorekeeper_info {
            get {
                return ResourceManager.GetString("RelaxAncientLorekeeper_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Tongues curse penalty 的本地化字符串。
        /// </summary>
        internal static string RelaxTonguesCurse_info {
            get {
                return ResourceManager.GetString("RelaxTonguesCurse_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 that party members need 1 rank Knowledge: World to be controlled by PC in combat 的本地化字符串。
        /// </summary>
        internal static string RelaxTonguesCurse_tip {
            get {
                return ResourceManager.GetString("RelaxTonguesCurse_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upon reaching {0}th level, and at every {1} {2} level after that ({3}th, {4}th, and so on), a {5} can choose to learn a new spell in place of one they already know. In effect, the {6} loses the old spell in exchange for the new one. The new spell&apos;s level must be the same as that of the spell being exchanged. A {7} may swap only a single spell at any given level, and must choose whether or not to swap the spell at the same time that they gain new spells known for the level. 的本地化字符串。
        /// </summary>
        internal static string ReplacementFeatureDescription_info {
            get {
                return ResourceManager.GetString("ReplacementFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace Spell ({0}) 的本地化字符串。
        /// </summary>
        internal static string ReplacementFeatureName_info {
            get {
                return ResourceManager.GetString("ReplacementFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result: failure. 的本地化字符串。
        /// </summary>
        internal static string ResultFailLog_info {
            get {
                return ResourceManager.GetString("ResultFailLog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result: success. 的本地化字符串。
        /// </summary>
        internal static string ResultSuccessLog_info {
            get {
                return ResourceManager.GetString("ResultSuccessLog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This spell functions like raise dead, except that you can resurrect a creature that has been dead for as long as 10 years per caster level.This spell can even bring back creatures whose bodies have been destroyed, provided that you unambiguously identify the deceased in some fashion(reciting the deceased&apos;s time and place of birth or death is the most common method).Upon completion of the spell, the creature is immediately restored to full hit points, vigor, and health, with no negative levels(or loss of * C [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ResurrectionSpellDescription_info {
            get {
                return ResourceManager.GetString("ResurrectionSpellDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whenever you cast a spell that cures the target of hit point damage, you do not provoke attacks of opportunity for spellcasting. 的本地化字符串。
        /// </summary>
        internal static string SafeCuringFeatureDescription_info {
            get {
                return ResourceManager.GetString("SafeCuringFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Safe Curing 的本地化字符串。
        /// </summary>
        internal static string SafeCuringFeatureName_info {
            get {
                return ResourceManager.GetString("SafeCuringFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Arcana ({0}) 的本地化字符串。
        /// </summary>
        internal static string ScionExtraArcanaFeatureName_info {
            get {
                return ResourceManager.GetString("ScionExtraArcanaFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show custom portraits in the portrait list at character creation (if changed, requires restart) 的本地化字符串。
        /// </summary>
        internal static string ShowCustomPortraits_info {
            get {
                return ResourceManager.GetString("ShowCustomPortraits_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • {0} 的本地化字符串。
        /// </summary>
        internal static string SingleLineDescription_info {
            get {
                return ResourceManager.GetString("SingleLineDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When a magus selects this arcana, they must select one spell from the wizard spell list that is of a magus spell level they can cast. They adds this spell to their spellbook and list of magus spells known as a magus spell of its wizard spell level. They can instead select two spells to add in this way, but both must be at least one level lower than the highest-level magus spell they can cast.
        ///Special: A magus can select this magus arcana more than once. 的本地化字符串。
        /// </summary>
        internal static string SpellBlendingFeatureDescription_info {
            get {
                return ResourceManager.GetString("SpellBlendingFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spell Blending 的本地化字符串。
        /// </summary>
        internal static string SpellBlendingFeatureName_info {
            get {
                return ResourceManager.GetString("SpellBlendingFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (After casting this spell, use the ability bar to select your {0}.)
        /// 的本地化字符串。
        /// </summary>
        internal static string SpellDescriptionPrefix_info {
            get {
                return ResourceManager.GetString("SpellDescriptionPrefix_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick one spell which you have the ability to cast. Whenever you cast that spell you may apply any one metamagic feat you have to that spell without affecting its level or casting time, as long as the total modified level of the spell does not use a spell slot above 9th level. In addition, if you have other feats which allow you to apply a set numerical bonus to any aspect of this spell (such as Spell Focus, Spell Penetration, Weapon Focus [ray], and so on), double the bonus granted by that feat when applied [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SpellPerfectionFeatureDescription_info {
            get {
                return ResourceManager.GetString("SpellPerfectionFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spell Perfection 的本地化字符串。
        /// </summary>
        internal static string SpellPerfectionFeatureName_info {
            get {
                return ResourceManager.GetString("SpellPerfectionFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Spells 的本地化字符串。
        /// </summary>
        internal static string SpellsSpellNamePostfix_info {
            get {
                return ResourceManager.GetString("SpellsSpellNamePostfix_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have {0} on saves vs {1} and elemental weakness {2}. 的本地化字符串。
        /// </summary>
        internal static string SpellVulnerabilityFeatureDescription_info {
            get {
                return ResourceManager.GetString("SpellVulnerabilityFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spell Vulnerability ({0}) 的本地化字符串。
        /// </summary>
        internal static string SpellVulnerabilityFeatureName_info {
            get {
                return ResourceManager.GetString("SpellVulnerabilityFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whenever your healing spells heal a target up to its maximum hit points, any excess points persist for 1 round per level as temporary hit points (up to a maximum number of temporary hit points equal to your oracle level). 的本地化字符串。
        /// </summary>
        internal static string SpiritBoostFeatureDescription_info {
            get {
                return ResourceManager.GetString("SpiritBoostFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spirit Boost 的本地化字符串。
        /// </summary>
        internal static string SpiritBoostFeatureName_info {
            get {
                return ResourceManager.GetString("SpiritBoostFeatureName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spiritual Weapon 的本地化字符串。
        /// </summary>
        internal static string SpritualWeaponSpells_info {
            get {
                return ResourceManager.GetString("SpritualWeaponSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You summon a swarm of Squirrels, which attacks all other creatures within its area. (You may summon the swarm so that it shares the area of other creatures.) If no living creatures are within its area, the swarm attacks or pursues the nearest creature as best it can. The caster has no control over its target or direction of travel. 的本地化字符串。
        /// </summary>
        internal static string SquirrelSpellDescription_info {
            get {
                return ResourceManager.GetString("SquirrelSpellDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summon Swarm Squirrels 的本地化字符串。
        /// </summary>
        internal static string SquirrelSpellName_info {
            get {
                return ResourceManager.GetString("SquirrelSpellName_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wild Hunt 的本地化字符串。
        /// </summary>
        internal static string SummonWildhuntSpells_info {
            get {
                return ResourceManager.GetString("SummonWildhuntSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;This mod was tested against game version {0}, but you are running {1}.&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string testedGameVersion_warning {
            get {
                return ResourceManager.GetString("testedGameVersion_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Stop 的本地化字符串。
        /// </summary>
        internal static string TimeStopSpells_info {
            get {
                return ResourceManager.GetString("TimeStopSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 True resurrection 的本地化字符串。
        /// </summary>
        internal static string TrueResurrectionSpells_info {
            get {
                return ResourceManager.GetString("TrueResurrectionSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You transform a single weapon into an awe-inspiring instrument. The weapon gains a +2 sacred bonus on damage rolls, and if the weapon scores a critical hit, the target of that critical hit becomes shaken for 1 round with no saving throw.
        ///This is a mind-affecting fear effect. A ranged weapon affected by this spell applies these effects to its ammunition.
        ///You can&apos;t cast this spell on a natural weapon, but you can cast it on an unarmed strike. 的本地化字符串。
        /// </summary>
        internal static string WeaponOfAweAbilityDescription_info {
            get {
                return ResourceManager.GetString("WeaponOfAweAbilityDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 +2 sacred bonus on damage rolls, and target is shaken for 1 round on critical hits. 的本地化字符串。
        /// </summary>
        internal static string WeaponofAweDescription_info {
            get {
                return ResourceManager.GetString("WeaponofAweDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon Of Awe 的本地化字符串。
        /// </summary>
        internal static string WeaponOfAweSpells_info {
            get {
                return ResourceManager.GetString("WeaponOfAweSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wish is the mightiest spell a wizard or sorcerer can cast. By simply speaking aloud, you can alter reality to better suit you. Even wish, however, has its limits. A wish can produce any one of the following effects.
        ///• Duplicate any sorcerer/wizard spell of 8th level or lower, provided the spell does not belong to one of your opposition schools.
        ///• Duplicate any non-sorcerer/wizard spell of 7th level or lower, provided the spell does not belong to one of your opposition schools.
        ///• Duplicate any sorcerer/wi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WishAbilityDescription_info {
            get {
                return ResourceManager.GetString("WishAbilityDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wish for a permanent inherent bonus to {0}.
        ///Two to five wish spells cast in immediate succession can grant a creature a +2 to +5 inherent bonus to an ability score (two wishes for a +2 inherent bonus, three wishes for a +3 inherent bonus, and so on). Inherent bonuses are instantaneous, so they cannot be dispelled. Note: An inherent bonus may not exceed +5 for a single ability score, and inherent bonuses to a particular ability score do not stack, so only the best one applies. 的本地化字符串。
        /// </summary>
        internal static string WishBuffDescription_info {
            get {
                return ResourceManager.GetString("WishBuffDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arcane Wish lets you create nearly any type of effect as long as you provide 5 diamonds is high enough.
        ///• Duplicate any sorcerer/wizard spell of 6th level or lower, provided the spell does not belong to one of your opposition schools.
        ///• Duplicate any non-sorcerer/wizard spell of 5th level or lower, provided the spell does not belong to one of your opposition schools.
        ///• Duplicate any sorcerer/wizard spell of 5th level or lower, even if it belongs to one of your opposition schools.
        ///• Duplicate any non-sor [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WishFabricateAbilityDescription_info {
            get {
                return ResourceManager.GetString("WishFabricateAbilityDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wish(Arcane) 的本地化字符串。
        /// </summary>
        internal static string WishFabricateSpells_info {
            get {
                return ResourceManager.GetString("WishFabricateSpells_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A wish granted a permanent inherent bonus to {0}. 的本地化字符串。
        /// </summary>
        internal static string WishFeatureDescription_info {
            get {
                return ResourceManager.GetString("WishFeatureDescription_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opposition school spells of this level are not available. 的本地化字符串。
        /// </summary>
        internal static string WishReason_error {
            get {
                return ResourceManager.GetString("WishReason_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wish 的本地化字符串。
        /// </summary>
        internal static string WishSpells_info {
            get {
                return ResourceManager.GetString("WishSpells_info", resourceCulture);
            }
        }
    }
}
